<a href="https://colab.research.google.com/github/kushkarki-okd/student_performance/blob/main/student_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import numpy as np
import pandas as pd

In [ ]:
drive.mount("/content/drive")
data=pd.read_csv("/content/drive/My Drive/data/student_activity.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data.head()

,Student_ID,Age,Gender,Study_Hours_Per_Day,Attendance_Percent,Previous_Exam_Marks,Assignment_Score,Sleep_Hours,Screen_Time_Hours,Internet_Access,Parental_Support,Extra_Classes,Final_Exam_Marks,Pass_Fail
0,STU01118,15.0,Male,3.8,62.0,42.0,59.5,8.5,7.5,Yes,Medium,No,42.5,Pass
1,STU03462,22.0,Female,1.7,100.0,52.9,66.8,7.4,2.8,Yes,High,No,68.3,Pass
2,STU02390,17.0,Female,4.4,73.5,60.8,85.8,7.3,3.0,NaN,High,No,70.6,Pass
3,STU00021,20.0,Male,4.1,66.1,64.2,68.0,7.5,5.9,No,High,No,39.5,Fail
4,STU00693,22.0,Female,6.4,85.6,41.5,43.4,8.3,3.8,Yes,Medium,No,43.0,Pass

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3595 entries, 0 to 3594
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           3595 non-null   object
 1   Age                  3485 non-null   float64
 2   Gender               3595 non-null   object
 3   Study_Hours_Per_Day  3504 non-null   float64
 4   Attendance_Percent   3543 non-null   object
 5   Previous_Exam_Marks  3501 non-null   float64
 6   Assignment_Score     3543 non-null   float64
 7   Sleep_Hours          3498 non-null   float64
 8   Screen_Time_Hours    3528 non-null   float64
 9   Internet_Access      3513 non-null   object
 10  Parental_Support     3523 non-null   object
 11  Extra_Classes        3472 non-null   object
 12  Final_Exam_Marks     3552 non-null   float64
 13  Pass_Fail            3550 non-null   object
dtypes: float64(7), object(7)
memory usage: 393.3+ KB

In [ ]:
data.isnull().sum()

Student_ID               0
Age                    110
Gender                   0
Study_Hours_Per_Day     91
Attendance_Percent      52
Previous_Exam_Marks     94
Assignment_Score        52
Sleep_Hours             97
Screen_Time_Hours       67
Internet_Access         82
Parental_Support        72
Extra_Classes          123
Final_Exam_Marks        43
Pass_Fail               45
dtype: int64

In [ ]:
data["Age"]=data["Age"].fillna(data["Age"].median())

In [ ]:
data["Study_Hours_Per_Day"]=data["Study_Hours_Per_Day"].fillna(data["Study_Hours_Per_Day"].median())

In [ ]:
data["Attendance_Percent"]=pd.to_numeric(data["Attendance_Percent"], errors="coerce")

In [ ]:
data["Attendance_Percent"]=data["Attendance_Percent"].fillna(data["Attendance_Percent"].median())

In [ ]:
data["Parental_Support"].unique()

array(['Medium', 'High', 'Low', nan, ' High ', 'MEDIUM', 'medium', 'low',
       ' Low ', 'HIGH', ' Medium ', 'LOW', 'high'], dtype=object)

In [ ]:
data["Parental_Support"]=data["Parental_Support"].replace({
    "HIGN":"High",
    "MEDIUM":"Medium",
    "medium":"Medium",
    "LOW":"Low",
    "low":"Low"
})

In [ ]:
data["Gender"].unique()

array(['Male', 'Female', 'Other', ' Female ', ' Male ', 'female', 'male',
       'FEMALE', 'MALE'], dtype=object)

In [ ]:
data["Gender"] = (
    data["Gender"]
    .str.strip()
    .str.lower()
    .map({"female": "Female", "male": "Male","other":"other"})
)

In [ ]:
data["Extra_Classes"].unique()

array(['No', 'Yes', 'no', 'yes', nan, ' No ', 'NO', 'YES', ' Yes '],
      dtype=object)

In [ ]:
data["Extra_Classes"] = (
    data["Extra_Classes"]
    .str.strip()
    .str.lower()
    .map({"yes": "Yes", "no": "No",})
)

In [ ]:
data["Pass_Fail"].unique()

array(['Pass', 'Fail', 'pass', ' Pass ', 'FAIL', nan, 'PASS', 'fail',
       ' Fail '], dtype=object)

In [ ]:
data["Pass_Fail"] = (
    data["Pass_Fail"]
    .str.strip()
    .str.lower()
    .map({"pass": "Pass","fail": "Fail"}))

In [ ]:
data["Internet_Access"]=(data["Internet_Access"].str.strip().str.lower().map({
    "yes":"Yes",
    "no":"No"
}))

In [ ]:
data["Previous_Exam_Marks"]=data["Previous_Exam_Marks"].fillna(data["Previous_Exam_Marks"].median())
data["Assignment_Score"]=data["Assignment_Score"].fillna(data["Assignment_Score"].median())
data["Screen_Time_Hours"]=data["Screen_Time_Hours"].fillna(data["Screen_Time_Hours"].median())
data["Sleep_Hours"]=data["Sleep_Hours"].fillna(data["Sleep_Hours"].median())
data["Internet_Access"]=data["Internet_Access"].fillna(data["Internet_Access"].mode()[0])
data["Extra_Classes"]=data["Extra_Classes"].fillna(data["Extra_Classes"].mode()[0])
data["Parental_Support"]=data["Parental_Support"].fillna(data["Parental_Support"].mode()[0])
data["Pass_Fail"]=data["Pass_Fail"].fillna(data["Pass_Fail"].mode()[0])
data["Final_Exam_Marks"]=data["Final_Exam_Marks"].fillna(data["Final_Exam_Marks"].median())

In [ ]:
data = data.drop(columns=["Student_ID", "Age"], errors="ignore")

In [ ]:
data=pd.get_dummies(data, columns=["Parental_Support","Internet_Access","Extra_Classes","Gender"],dtype=int)

In [ ]:
data.head()

,Study_Hours_Per_Day,Attendance_Percent,Previous_Exam_Marks,Assignment_Score,Sleep_Hours,Screen_Time_Hours,Final_Exam_Marks,Pass_Fail,Parental_Support_ High,Parental_Support_ Low,...,Parental_Support_Low,Parental_Support_Medium,Parental_Support_high,Internet_Access_No,Internet_Access_Yes,Extra_Classes_No,Extra_Classes_Yes,Gender_Female,Gender_Male,Gender_other
0,3.8,62.0,42.0,59.5,8.5,7.5,42.5,Pass,0,0,...,0,1,0,0,1,1,0,0,1,0
1,1.7,100.0,52.9,66.8,7.4,2.8,68.3,Pass,0,0,...,0,0,0,0,1,1,0,1,0,0
2,4.4,73.5,60.8,85.8,7.3,3.0,70.6,Pass,0,0,...,0,0,0,0,1,1,0,1,0,0
3,4.1,66.1,64.2,68.0,7.5,5.9,39.5,Fail,0,0,...,0,0,0,1,0,1,0,0,1,0
4,6.4,85.6,41.5,43.4,8.3,3.8,43.0,Pass,0,0,...,0,1,0,0,1,1,0,1,0,0

In [ ]:
# Numerical columns only
numeric_columns = data.select_dtypes(include="number").columns

# Remove target columns if you are using them for prediction
# Change/remove these according to your ML task
exclude_columns = ["Pass_Fail","Final_Exam_Marks"]

numeric_columns = [
    col for col in numeric_columns
    if col not in exclude_columns
]

# Create a mask: initially keep all rows
mask = pd.Series(True, index=data.index)

# IQR method
for column in numeric_columns:

    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Keep values inside the normal range
    mask &= (
        (data[column] >= lower_bound) &
        (data[column] <= upper_bound)
    )

# Remove all rows containing outliers
data = data[mask].copy()

# Reset index
data.reset_index(drop=True, inplace=True)

print("Data shape after removing outliers:", data.shape)

Data shape after removing outliers: (2048, 23)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.svm import SVR

In [ ]:
x=data.drop(columns=["Pass_Fail","Final_Exam_Marks"],axis=True)
y_classifacation=data["Pass_Fail"]
y_regeration=data["Final_Exam_Marks"]

In [ ]:
X_train, X_test, y_class_train, y_class_test = train_test_split(
    x,
    y_classifacation,
    test_size=0.2,
    random_state=42,
    stratify=y_classifacation
)

X_train_reg = X_train
X_test_reg = X_test

y_reg_train = y_regeration.loc[X_train.index]
y_reg_test = y_regeration.loc[X_test.index]

In [ ]:
classification_models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC()
}
classification_results = []
for name,model in classification_models.items():
  model.fit(X_train,y_class_train)
  y_predict=model.predict(X_test)

  classification_results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_class_test, y_predict),
        "Precision": precision_score(
            y_class_test,
            y_predict,
            pos_label="Pass",
            zero_division=0
        ),
        "Recall": recall_score(
            y_class_test,
            y_predict,
            pos_label="Pass",
            zero_division=0
        ),
        "F1 Score": f1_score(
            y_class_test,
            y_predict,
            pos_label="Pass",
            zero_division=0
        )
    })

classification_results = pd.DataFrame(classification_results)

print(classification_results)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.939024   0.941176  0.997403  0.968474
1        Decision Tree  0.912195   0.953247  0.953247  0.953247
2                  KNN  0.936585   0.943210  0.992208  0.967089
3        Random Forest  0.948780   0.948276  1.000000  0.973451
4                  SVM  0.939024   0.939024  1.000000  0.968553

In [ ]:
regression_models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "KNN": KNeighborsRegressor(),
    "Random Forest": RandomForestRegressor(random_state=42),
    "SVR": SVR()
}

regression_results = []

for name, model in regression_models.items():

    model.fit(X_train, y_reg_train)

    y_predict = model.predict(X_test)

    regression_results.append({
        "Model": name,
        "MAE": mean_absolute_error(y_reg_test, y_predict),
        "RMSE": np.sqrt(mean_squared_error(y_reg_test, y_predict)),
        "R2 Score": r2_score(y_reg_test, y_predict)
    })

regression_results = pd.DataFrame(regression_results)

print(regression_results)

               Model        MAE       RMSE  R2 Score
0  Linear Regression   8.419218  10.520550  0.467418
1      Decision Tree  12.523659  16.047911 -0.239215
2                KNN  10.032341  12.464910  0.252368
3      Random Forest   8.418949  10.684990  0.450639
4                SVR   9.514710  11.853580  0.323903