<a href="https://colab.research.google.com/github/kushkarki-okd/student_performance/blob/main/student_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from google.colab import drive
import numpy as np

In [4]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
data=pd.read_csv("/content/drive/My Drive/student performance /student_performance_messy_dataset.csv")

In [6]:
data.head(8)

,Student_ID,Name,Age,Gender,Attendance,Study_Hours,Internet_Access,Sleep_Hours,Assignments,Final_Grade
0,S001,Aarav,17.0,Male,92%,3.5,Yes,7,9,88
1,S002,Sita,16.0,Female,85,2.0,Yes,6.5,8,76
2,S003,Ram,NaN,male,78%,NaN,No,5,6,65
3,S004,Hari,-1.0,Male,101%,10,YES,3,10,95
4,S005,Gita,17.0,Female,absent,1.5,yes,NaN,4,55
5,S006,Nabin,18.0,M,90 %,4.5,No,8,9,91
6,S006,Nabin,18.0,M,90 %,4.5,No,8,9,91
7,S007,Puja,16.0,Female,70%,-2,Yes,9,5,60

In [7]:
data.isnull().sum()

Student_ID         0
Name               0
Age                1
Gender             0
Attendance         1
Study_Hours        1
Internet_Access    0
Sleep_Hours        1
Assignments        0
Final_Grade        1
dtype: int64

In [8]:
data.shape

(16, 10)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student_ID       16 non-null     object
 1   Name             16 non-null     object
 2   Age              15 non-null     float64
 3   Gender           16 non-null     object
 4   Attendance       15 non-null     object
 5   Study_Hours      15 non-null     object
 6   Internet_Access  16 non-null     object
 7   Sleep_Hours      15 non-null     object
 8   Assignments      16 non-null     object
 9   Final_Grade      15 non-null     object
dtypes: float64(1), object(9)
memory usage: 1.4+ KB

In [10]:
data["Age"]=data["Age"].replace(-1,np.nan)

In [11]:
data["Age"]=data["Age"].fillna(data["Age"].median())

In [12]:
data["Age"]

0      17.0
1      16.0
2      17.0
3      17.0
4      17.0
5      18.0
6      18.0
7      16.0
8      17.0
9      16.0
10     17.0
11     19.0
12     16.0
13     17.0
14    120.0
15     15.0
Name: Age, dtype: float64

In [13]:
data["Study_Hours"]=pd.to_numeric(data["Study_Hours"],errors="coerce")

In [14]:
data["Study_Hours"]=data["Study_Hours"].fillna(data["Study_Hours"].mean())

In [15]:
data["Attendance"]=pd.to_numeric(data["Attendance"],errors="coerce")
data["Attendance"]=data["Attendance"].fillna(data["Attendance"].mean())

In [16]:
data["Final_Grade"]=pd.to_numeric(data["Final_Grade"],errors="coerce")
data["Final_Grade"]=data["Final_Grade"].fillna(data["Final_Grade"].mean())

In [17]:
data.isnull().sum()

Student_ID         0
Name               0
Age                0
Gender             0
Attendance         0
Study_Hours        0
Internet_Access    0
Sleep_Hours        1
Assignments        0
Final_Grade        0
dtype: int64

In [18]:
data["Sleep_Hours"]=pd.to_numeric(data["Sleep_Hours"],errors='coerce')
data["Sleep_Hours"]=data["Sleep_Hours"].fillna(data["Sleep_Hours"].mean())

In [19]:
data.head()

,Student_ID,Name,Age,Gender,Attendance,Study_Hours,Internet_Access,Sleep_Hours,Assignments,Final_Grade
0,S001,Aarav,17.0,Male,85.0,3.500000,Yes,7.000000,9,88.0
1,S002,Sita,16.0,Female,85.0,2.000000,Yes,6.500000,8,76.0
2,S003,Ram,17.0,male,85.0,3.735714,No,5.000000,6,65.0
3,S004,Hari,17.0,Male,85.0,10.000000,YES,3.000000,10,95.0
4,S005,Gita,17.0,Female,85.0,1.500000,yes,6.285714,4,55.0

In [20]:
data["Gender"].unique()

array(['Male', 'Female', 'male', 'M', 'F'], dtype=object)

In [21]:
data["Gender"]=data["Gender"].replace({
    "M":"Male",
    "male":"Male",
    "F":"Female"
})

In [22]:
data["Internet_Access"].unique()

array(['Yes', 'No', 'YES', 'yes', 'Unknown'], dtype=object)

In [23]:
data["Internet_Access"]=data["Internet_Access"].replace({
    "YES":"yes",
    "Yes":"yes",

})

In [24]:
data.duplicated().sum()

np.int64(1)

In [25]:
data = data.drop_duplicates()

In [26]:
data["Gender"]=data["Gender"].map({
    "Male":1,
    "Female":0
})

In [27]:
data=pd.get_dummies(data,columns=["Internet_Access"],dtype=int)

In [28]:
data=data.drop(["Student_ID","Name"],axis=1)

In [29]:
data["Assignments"]=data["Assignments"].replace({"Nine":9})

In [30]:
data.head()

,Age,Gender,Attendance,Study_Hours,Sleep_Hours,Assignments,Final_Grade,Internet_Access_No,Internet_Access_Unknown,Internet_Access_yes
0,17.0,1,85.0,3.500000,7.000000,9,88.0,0,0,1
1,16.0,0,85.0,2.000000,6.500000,8,76.0,0,0,1
2,17.0,1,85.0,3.735714,5.000000,6,65.0,1,0,0
3,17.0,1,85.0,10.000000,3.000000,10,95.0,0,0,1
4,17.0,0,85.0,1.500000,6.285714,4,55.0,0,0,1

In [31]:
data.isnull().sum()

Age                        0
Gender                     0
Attendance                 0
Study_Hours                0
Sleep_Hours                0
Assignments                0
Final_Grade                0
Internet_Access_No         0
Internet_Access_Unknown    0
Internet_Access_yes        0
dtype: int64

In [32]:
data.describe()

,Age,Gender,Attendance,Study_Hours,Sleep_Hours,Final_Grade,Internet_Access_No,Internet_Access_Unknown,Internet_Access_yes
count,15.000000,15.000000,15.0,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,23.666667,0.533333,85.0,3.684762,6.171429,78.504762,0.266667,0.066667,0.666667
std,26.666369,0.516398,0.0,3.378176,1.788903,13.518464,0.457738,0.258199,0.487950
min,15.000000,0.000000,85.0,-2.000000,2.000000,55.000000,0.000000,0.000000,0.000000
25%,16.000000,0.000000,85.0,2.250000,5.750000,70.500000,0.000000,0.000000,0.000000
50%,17.000000,1.000000,85.0,3.200000,6.500000,79.285714,0.000000,0.000000,1.000000
75%,17.000000,1.000000,85.0,3.767857,7.100000,87.500000,0.500000,0.000000,1.000000
max,120.000000,1.000000,85.0,12.000000,9.000000,99.000000,1.000000,1.000000,1.000000

In [33]:
data.head(15)

,Age,Gender,Attendance,Study_Hours,Sleep_Hours,Assignments,Final_Grade,Internet_Access_No,Internet_Access_Unknown,Internet_Access_yes
0,17.0,1,85.0,3.500000,7.000000,9,88.000000,0,0,1
1,16.0,0,85.0,2.000000,6.500000,8,76.000000,0,0,1
2,17.0,1,85.0,3.735714,5.000000,6,65.000000,1,0,0
3,17.0,1,85.0,10.000000,3.000000,10,95.000000,0,0,1
4,17.0,0,85.0,1.500000,6.285714,4,55.000000,0,0,1
5,18.0,1,85.0,4.500000,8.000000,9,91.000000,1,0,0
7,16.0,0,85.0,-2.000000,9.000000,5,60.000000,0,0,1
8,17.0,1,85.0,12.000000,2.000000,11,99.000000,0,1,0
9,16.0,0,85.0,3.000000,6.285714,7,82.000000,0,0,1
10,17.0,1,85.0,2.500000,6.000000,7,79.285714,1,0,0
11,19.0,0,85.0,3.735714,7.500000,8,87.000000,0,0,1
12,16.0,1,85.0,3.200000,6.800000,9,79.000000,0,0,1
13,17.0,0,85.0,2.800000,7.200000,7,79.285714,1,0,0
14,120.0,1,85.0,3.800000,6.500000,8,84.000000,0,0,1
15,15.0,0,85.0,1.000000,5.500000,3,58.000000,0,0,1

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [35]:
x = data.drop("Final_Grade",axis=1)
y = data["Final_Grade"]

In [40]:
x_Train,x_Test,y_Train,y_Test = train_test_split(x,y,test_size=0.2,random_state=42)
scalar=StandardScaler()
x_Train_scaled_data=scalar.fit_transform(x_Train)
x_Test_scaled_data=scalar.fit_transform(x_Test)

model=LinearRegression()
model.fit(x_Train_scaled_data,y_Train)
y_predict=model.predict(x_Train_scaled_data)